### ISSUE TITLE
OpenDHBackend gives me Unhandled Exception : System.io.filenotfoundexception then closes cmd

### ISSUE THREAD

**Issue by tryingsomethinggg** [iLinked1337/OpenDiscordHaxx#15]
it says that the system cannot find the file specified.
at DiscordHaxx.SocketServer.Start()
at DiscordHaxx.Program.Main() in C:\Users\ilink......Program.cs:line 14

Anyone knows whats the problem and how to fix?

**Comment by datboimayor** [comment]
https://i.imgur.com/zMw0rzf.png

Same here.

**Comment by Jsstin** [comment]
> it says that the system cannot find the file specified.
> at DiscordHaxx.SocketServer.Start()
> at DiscordHaxx.Program.Main() in C:\Users\ilink......Program.cs:line 14
> 
> Anyone knows whats the problem and how to fix?

ik how to fix. all you have to do is go in bin. in DEBUG, bc in realeses it doesnt work
